name = "template"
workers_dev = true
compatibility_date = "2022-05-15"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

routes = [
	{ pattern = "dev.ardeshir.io", custom_domain = true, zone_name = "ardeshir.io" }
]

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
